# Generated by Django 5.1.6 on 2025-02-21 12:37

from django.db import migrations
from django.utils.text import slugify

def populate_category_slugs(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save()

def reverse_populate_category_slugs(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_category_slugs, reverse_populate_category_slugs),
    ]
